name: CMake

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: ubuntu-latest-gcc-cmake
            os: ubuntu-latest
            cc: gcc
            cxx: g++
            build-system: cmake
            cmake-opts: ''

          - name: ubuntu-latest-clang-cmake
            os: ubuntu-latest
            cc: clang
            cxx: clang++
            build-system: cmake
            cmake-opts: ''

          - name: ubuntu-24.04-arm-clang-cmake
            os: ubuntu-24.04-arm
            cc: clang
            cxx: clang++
            build-system: cmake
            cmake-opts: ''

          - name: ubuntu-latest-clang-cmake-asan-fuzzer
            os: ubuntu-latest
            cc: clang
            cxx: clang++
            build-system: cmake
            cmake-opts: '-DSANITIZE=fuzzer-no-link,address'

          - name: ubuntu-latest-clang-cmake-ninja
            os: ubuntu-latest
            cc: clang
            cxx: clang++
            build-system: cmake
            cmake-opts: '-G Ninja'

          - name: macos-latest-clang-cmake
            os: macos-latest
            cc: clang
            cxx: clang++
            build-system: cmake
            cmake-opts: ''

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux dependencies
      if: startsWith(matrix.os,'ubuntu') && contains(matrix.cmake-opts,'-G Ninja')
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Configure CMake
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cmake -B ${{github.workspace}}/out -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{ matrix.cmake-opts }}

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{env.BUILD_TYPE}}
